global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/prometheus/metrics"

  # Monitor Nginx via exporter (internal network only)
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx_exporter:9113"]
    scrape_interval: 30s

  # Monitor MariaDB via exporter (internal network only)
  - job_name: "mariadb_exporter"
    static_configs:
      - targets: ["mariadb_exporter:9104"]
    scrape_interval: 30s


# Monitor Redis via exporter (internal network only)
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]
    scrape_interval: 30s
