services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./services/mariadb
    image: mariadb:custom
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./services/nginx
    image: nginx:custom
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: ./services/wordpress
    image: wordpress:custom
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"

  redis:
    container_name: redis
    build: ./services/bonus/redis
    image: redis:custom
    restart: always
    networks:
      - inception
    volumes:
      - redis:/var/lib/redis
    env_file:
      - .env
    depends_on:
      - mariadb

  ftp:
    container_name: ftp
    build: ./services/bonus/ftp
    image: ftp:custom
    env_file:
      - .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress:/home/${FTP_USER}/ftp
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      #device: /home/denuen/data/mariadb
      device: /Users/denuen/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      #device: /home/denuen/data/wordpress
      device: /Users/denuen/data/wordpress
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /Users/denuen/data/redis
      o: bind
  ftp:
    driver: local
    driver_opts:
      type: none
      device: /Users/denuen/data/ftp
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
