CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MYSQL_ROOT_PASSWORD}');
FLUSH PRIVILEGES;

DROP USER IF EXISTS '${MARIADB_EXPORTER_USER}'@'%';
CREATE USER '${MARIADB_EXPORTER_USER}'@'%' IDENTIFIED BY '${MARIADB_EXPORTER_PASS}';
GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR, SELECT ON *.* TO '${MARIADB_EXPORTER_USER}'@'%';
FLUSH PRIVILEGES;
